[WIP] Adds authentication to POST widgets/:id
kittoframework/kitto pull request #11
Opened 2016-11-12 18:43 UTC by davejlong

To resolve #6, `POST widgets/:id` now supports token based
authentication. It can be configured through Mix with:

    config :kitto, auth_token: "mysecrettoken"

Setting the `auth_token` key will enforce authentication to `POST
widgets/:id` using the Authentication HTTP header:

    Authorization: Token mysecrettoken

2016-11-13 16:47 UTC, zorbash requested changes

2016-11-13 16:47 UTC, Zorbash commented on test/router_test.exs
> +  test "with auth token post widgets/:id denies access when provided" do
Change `denies` to grants access in test description.

2016-11-13 16:47 UTC, Zorbash commented on test/router_test.exs
> +    Application.put_env :kitto, :auth_token, "foobar"
Can you change "foobar" to "asecret"?

2016-11-13 16:47 UTC, Zorbash commented on test/router_test.exs
> +  end
I think we need one more test here for the case where `auth_token` is not set at all.

2016-11-13 16:47 UTC, Zorbash commented on lib/kitto/router.ex
> +    Application.get_env(:kitto, :auth_token) == conn
I'd split the token fetching to a function.

```elixir
  defp auth_token, do: Application.get_env(:kitto, :auth_token)
```

2016-11-13 16:47 UTC, Zorbash commented on lib/kitto/router.ex
> +  defp authenticate(conn) do
This seems like a good candidate for a predicate function, since it'll always return true || false like:

```elixir
defp authenticated?(conn)
```

2016-11-13 16:47 UTC, Zorbash commented on lib/kitto/router.ex
> +    if Application.get_env(:kitto, :auth_token) && !authenticate(conn) do
I suggest changing this part to:

```elixir
if authentication_required && !authenticated?(conn) do
```

With `authentication_required` defined as:

```elixir
  defp authentication_required?, do: !!auth_token
```

2016-11-14 13:29 UTC, davejlong commented on test/router_test.exs
> +  end
I think that isn't extremely necessary, since the rest of the tests effectively test that for us, especially at L#145.

2016-11-14 14:47 UTC, Zorbash commented on lib/kitto/router.ex
> +  defp auth_token, do: Application.get_env(:kitto, :auth_token)
Should the user be able to set the auth_token via env variable?

2016-11-14 14:48 UTC, Zorbash commented on test/router_test.exs
> +  end
You're right.

2016-11-14 14:50 UTC, davejlong commented on lib/kitto/router.ex
> +  defp auth_token, do: Application.get_env(:kitto, :auth_token)
What I typically do when I want to set something to the app env from system env is add the following to my `config/config.exs`:

```
config :kitto, auth_token: System.get_env("AUTH_TOKEN")
```

Whenever possible, I'm of the opinion that devs shouldn't use `System.get_env` in their application code.

2016-11-14 14:51 UTC, zorbash approved these changes
I'll cherry-pick this one (c044ec71a6) directly on master (it's a bit unrelated to the rest of the changes).

Edit: The commit also touches the tests added, so i won't.

2016-11-14 15:26 UTC, zorbash commented on lib/kitto/router.ex
> +  defp auth_token, do: Application.get_env(:kitto, :auth_token)
For the host and port configuration values, i think respecting the phoenix convention (https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint.ex#L132) is the intuitive way to go. For the auth_token let's leave it as is.

2016-11-14 18:05 UTC, davejlong commented
@Zorbash if all looks good so far, can you merge? In the future, I'm going to yank the authentication code out so it can be reused for other functionality like if we implement a reload feature similar to Dashing's for reloading dashboards remotely.

2016-11-14 20:15 UTC, Zorbash commented
:+1:  Looks good, merging it. As far as the dashboard reloading feature you're mentioning, better create an issue about this, so that it gets in the roadmap.

2016-11-14 20:26 UTC, merged